### ISSUE TITLE
Possibly Over Accessible Firewall

### ISSUE THREAD

**Issue by chris-barry** [m6urns/i2pberry#1]
Hi,

When opening ports for the firewall, I am unsure why ports that aren't SSH or I2P are opened. I assume this would normally be to allow the Pi to be a network device, but I don't see IRC or HTTP binding to 0.0.0.0 since i2ptunnel.config is the default. AFAIK the default binds to 127.0.0.1.

Lines in question:
https://github.com/m6urns/i2pberry/blob/master/i2p-setup#L140-L143

**Comment by m6urns** [comment]
4444 and 4445 are the ports i2p serves its http and https proxys on respectively. These are opened because it is assumed that this is a service most users of a I2P router would be interested in. Inorder to take advantage of these services the user needs to bind their services to 0.0.0.0 just as they need to manually bind port 7657 to 0.0.0.0 to take advantage of the web UI. You are correct that all I2P services by default bind to 127.0.0.1

If you feel that having these ports opened by the installation script is a security issue, I can easily change it and give a more detailed description of how to open the firewall to traffic.

**Comment by chris-barry** [comment]
Okay, so a manual procees *is* still required. It would be safe to assume you keep them open incase someone switches http{,s} from binding to 127.0.0.1 to 0.0.0.0?

I can't think of how this could be a security issue, since they are by default not listening at all.

**Comment by m6urns** [comment]
My thought exactly, opening those ports just simplifies the configuration process. Because the end user still has to make the decision to switch the bindings, it doesn't compromise the overall security of the installation.
