### ISSUE TITLE
Readme unclear

### ISSUE THREAD

**Issue by ismay** [m6urns/i2pberry#2]
I apologise in advance if this is a stupid question, but since you love suggestions I thought I might ask. It wasn't clear to me from the readme and other documentation on the web whether i2pberry intends to act as an access point (like the onionpi) without any extra configuration.

What exactly is the intended use case? Would an rpi with a wifi adapter (and an ethernet connection for the outgoing traffic) be able to act as an access point?

**Comment by mr-fool** [comment]
I intend to use it as a rasp/ nas computer not access point

**Comment by ismay** [comment]
Ah ok, good to know. Thanks for clarifying!

**Comment by ismay** [comment]
Ah sorry, thought I'd close the door behind me, so to speak.

**Comment by m6urns** [comment]
It is intended to function as a router for i2p traffic. Essentially a proxy host. With some configuration you could use it as an access point like the onionpi. 
I did not intend for configuration to be as easy as onionpi because I believe this leads to mistakes, that may compromise user security. Because every situation is different, having the user educate themselves about different configuration options and then configure the router makes them more conscious of their security choices, hopefully making users safer.

**Comment by ismay** [comment]
> Because every situation is different, having the user educate 
themselves about different configuration options and then configure the 
router makes them more conscious of their security choices, hopefully 
making users safer.

Ah ok, that makes sense. Though I could also see the value of providing 
sane defaults, to help users who otherwise wouldn't even try to use it. 
Then the learning curve could be a bit more gradual maybe.

**Comment by mr-fool** [comment]
The problem is i2p is that it is way harder to configure than tor and most people are not tech savvy. 
Then again, a 10 mins video like this https://www.youtube.com/watch?v=kz4q06jdlCE will do
